### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by MerlinB** [tokenized/spynode#3]
When running main.go the service runs fine, when doing the same in `bitcoin.TestNet` I get this:

```
panic: runtime error: index out of range [0] with length 0

goroutine 168 [running]:
github.com/tokenized/bitcoin_reader.(*NodeManager).nextNode(0xc000261540, {0xb459d8, 0xc0003512c0}, 0x0)
        /home/merlin/Devel/bitcoin_reader/node_manager.go:222 +0xc85
github.com/tokenized/bitcoin_reader.(*NodeManager).RequestTxs(0xc000261540, {0xb459d8, 0xc00030f5c0})
        /home/merlin/Devel/bitcoin_reader/node_manager.go:161 +0x171
github.com/tokenized/pkg/threads.(*Thread).runPeriodic(0xc00056af00, {0xb459d8, 0xc00030f5c0})
        /home/merlin/Devel/pkg/mod/github.com/tokenized/pkg@v0.4.1-0.20220524020344-6bbdcf489d31/threads/threads.go:216 +0xa5
github.com/tokenized/pkg/threads.(*Thread).Start.func1()
        /home/merlin/Devel/pkg/mod/github.com/tokenized/pkg@v0.4.1-0.20220524020344-6bbdcf489d31/threads/threads.go:179 +0x150
created by github.com/tokenized/pkg/threads.(*Thread).Start
        /home/merlin/Devel/pkg/mod/github.com/tokenized/pkg@v0.4.1-0.20220524020344-6bbdcf489d31/threads/threads.go:169 +0x17a
exit status 2
```

In the log I'm seeing lots of "connection refused" when trying to connect to nodes.

**Comment by MerlinB** [comment]
Never mind, this happens on Mainnet as well. I was not yet able to figure out a pattern, sometimes it seems to works.

The last message in the log is always something like `Finished: Node: [54.243.212.219]:8333: connect: dial tcp 54.243.212.219:8333: i/o timeout`

**Comment by MerlinB** [comment]
Sorry, accidentally opened this in the wrong repo! This regards bitcoin_reader. I will move it
